/* Generated By:JJTree: Do not edit this line. ASTconst_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTconst_decl extends SimpleNode {
  public ASTconst_decl(int id) {
    super(id);
  }

  public ASTconst_decl(basicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(basicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d7fe1be8f252adf1fb0e703017f75cb (do not edit this line) */
