/* Generated By:JJTree: Do not edit this line. ASTIdList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIdList extends SimpleNode {
  public ASTIdList(int id) {
    super(id);
  }

  public ASTIdList(basicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(basicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=38be02b4d256ed492416f6ef7f8225b5 (do not edit this line) */
