/* Generated By:JJTree: Do not edit this line. ASTmain_prog.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTmain_prog extends SimpleNode {
  public ASTmain_prog(int id) {
    super(id);
  }

  public ASTmain_prog(basicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(basicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=685a08f934cfde2e1cba41c3cb6439ac (do not edit this line) */
