/* Generated By:JJTree: Do not edit this line. ASTparam_list.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTparam_list extends SimpleNode {
  public ASTparam_list(int id) {
    super(id);
  }

  public ASTparam_list(basicL p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(basicLVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89aeaa9dcef2cffec350dc4f28822e76 (do not edit this line) */
