/* Generated By:JavaCC: Do not edit this line. basicL_ASTVisitor.java Version 5.0 */
public interface basicL_ASTVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVarDecl node, Object data);
  public Object visit(ASTconst_decl node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTparam_list node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTmain_prog node, Object data);
  public Object visit(ASTCondition node, Object data);
  public Object visit(ASTIdList node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTId node, Object data);
}
/* JavaCC - OriginalChecksum=3585dc191769204d20588113daa1809d (do not edit this line) */
