/* Generated By:JavaCC: Do not edit this line. basicL_ASTTreeConstants.java Version 5.0 */
public interface basicL_ASTTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTPARAM_LIST = 5;
  public int JJTTYPE = 6;
  public int JJTMAIN_PROG = 7;
  public int JJTTERM = 8;
  public int JJTCONDITION = 9;
  public int JJTIDLIST = 10;
  public int JJTNUMBER = 11;
  public int JJTID = 12;
  public int JJTEXPRESSIONWITHBRACKETS = 13;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VarDeclaration",
    "const_decl",
    "Function",
    "param_list",
    "Type",
    "main_prog",
    "Term",
    "Condition",
    "IdList",
    "Number",
    "Id",
    "ExpressionwithBrackets",
  };
}
/* JavaCC - OriginalChecksum=06bbe577bfbd7c0201cd63ba216a9915 (do not edit this line) */
