/* Generated By:JavaCC: Do not edit this line. basicLTreeConstants.java Version 5.0 */
public interface basicLTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARDECL = 2;
  public int JJTCONST_DECL = 3;
  public int JJTFUNCTION = 4;
  public int JJTPARAM_LIST = 5;
  public int JJTTYPE = 6;
  public int JJTMAIN_PROG = 7;
  public int JJTFUNCTIONCALL = 8;
  public int JJTCONDITION = 9;
  public int JJTIDLIST = 10;
  public int JJTNUMBER = 11;
  public int JJTID = 12;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VarDecl",
    "const_decl",
    "Function",
    "param_list",
    "Type",
    "main_prog",
    "FunctionCall",
    "Condition",
    "IdList",
    "Number",
    "Id",
  };
}
/* JavaCC - OriginalChecksum=0415282556fbce9b152e86e822f9a063 (do not edit this line) */
